### ISSUE TITLE
如何配置环境变量

### ISSUE THREAD

**Issue by huangang** [koahubjs/koahub#5]
框架好像没有设置多个环境变量的功能，一般我们都会有需求，本地开发是一个配置，测试运行是一个配置，正式发布后又是另外一个配置，框架是否会提供这个功能

**Comment by einsqing** [comment]
环境配置上只有一个参数，process.env.NODE_ENV。设置这个参数之后，只有日志的显示上有区别，其他的目前还没有加入。不知道你具体需要的是什么样的？

**Comment by huangang** [comment]
其实就是类似thinkjs[配置](https://thinkjs.org/zh-cn/doc/2.2/config.html)的功能,或者是像laravel写`env`那样设置环境变量

**Comment by einsqing** [comment]
OK，我们考虑下，看如何设计更简单好用。
