### ISSUE TITLE
express中间件兼容问题及开源协议

### ISSUE THREAD

**Issue by zeromake** [koahubjs/koahub#6]
[expressMiddlewareToKoaMiddleware](https://github.com/koahubjs/koahub/blob/master/src/util/default.util.js#L20)
这个兼容不好吧，express中间件是通过res.end和next来确定中间件结束的。
Promise只有next有回调处理。
例如[webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L27-L33)直接无参调用next

我觉得至少写上end处理，要不然用个中间件直接卡着后面的中间件了。
``` javascript
export function expressMiddlewareToKoaMiddleware(fn) {
    return function (ctx, next) {
        return new Promise((resolve, reject) => {
            const end = ctx.res.end
            ctx.res.end = function(){
                 end.apply(this, arguments)
                 resolve()
            }
            fn(ctx.req, ctx.res, reject)
        }).catch(next)
    }
}
```
还有些ctx.res里没有的方法但是express是有的。。

最后问下没有开源协议吗？

**Comment by einsqing** [comment]
koahub.js目前只是兼容部分express中间件，只能尽量多的兼容express中间件，我试试无参调用next的。开源协议是MIT

**Comment by zeromake** [comment]
@einsqing 顺便问下后面会有集成代码覆盖率报告吗？

**Comment by einsqing** [comment]
会的，接下来会尽量多的写测试。
