### ISSUE TITLE
child route default method

### ISSUE THREAD

**Issue by rockkratos** [koahubjs/koahub#7]
Hi，

在2.1.0版本中，子路由没有办法自动加载index方法了。

比如目录结构是/abc/test/index.controller.js，请求URL为/abc/test这时是会报404的，但是2.0.3就没问题。

这时必须把URL写成/abc/test/index/index才行。

**Comment by einsqing** [comment]
如果访问/abc/test，abc肯定是module，test是控制器，所以已经匹配出控制器了，换成index控制器不合理。需要访问/abc/test/index才行。
