### ISSUE TITLE
上传静态文件需要重启服务的问题

### ISSUE THREAD

**Issue by powa2005** [koahubjs/koahub#8]
Hi，
    请教下，我在后台上传图片，或者直接在文件夹新增文件的时候都需要重启服务才能访问，否则报404.

**Comment by einsqing** [comment]
你是如何写的？上传图片不需要重启服务器。

**Comment by powa2005** [comment]
koahub-simple-cms
down的这个源码，跑起来后里面的上传图片功能上传成功后的 图片访问是404，需要重启服务。
另外自己添加了html之后写的路由。也是会提示找不到资源，重启后问题解决。

**Comment by einsqing** [comment]
我们官网后台现在还在用koahub-simple-cms，并没有这个问题。你上传图片之后，图片管理器不会立即出现吗？更改什么配置没？

**Comment by powa2005** [comment]
![qq 20170407153101](https://cloud.githubusercontent.com/assets/8063309/24789965/d225add6-1ba7-11e7-8a1f-10368572c339.png)
这是我刚刚重新clone的koahub-simple-cms，只修改了mysql的config，其他不变。上传图片后本地文件夹是有内容的，但是请求的时候就是404，诡异

**Comment by einsqing** [comment]
确实很诡异，我再测试测试，什么环境，什么系统？

**Comment by powa2005** [comment]
win10, node -v 7.7.3

**Comment by einsqing** [comment]
因为使用了koa-static-cache，默认不是动态加载的。设置成true就可以了。
`
// app/config/middleware.config.js
static: {
        dir: 'www',
        dynamic: true
}
`
